FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    bash \
    nano \
    htop \
    git \
    curl \
    texlive-latex-base \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-fonts-recommended \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install --production

COPY . .

CMD ["node", "bot.js"]
