FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    bash \
    nano \
    htop \
    git \
    curl \
    docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# CMD ["/bin/bash"]
# CMD ["tail", "-f", "/dev/null"]
CMD ["python", "bot.py"]
